
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import FloatingCTA from "@/components/ui/FloatingCTA";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="h-full w-full">
      <body
        className={`min-h-screen w-full bg-gradient-to-br from-slate-100 via-white to-blue-50 text-slate-900 dark:bg-gradient-to-br dark:from-slate-900 dark:via-slate-800 dark:to-blue-950 dark:text-slate-100 ${geistSans.variable} ${geistMono.variable} antialiased font-sans flex flex-col h-full`}
        style={{ minHeight: '100dvh' }}
      >
        <Header />
        <FloatingCTA />
        <main className="container mx-auto flex-1 flex flex-col w-full px-4 sm:px-6 md:px-8 pt-20 gap-6 lg:grid lg:grid-cols-12 lg:max-w-screen-xl">
          <div className="col-span-12 flex flex-col w-full">
            {children}
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
